name: CICD TO EC2

on: 
  #pull_request: 
  # types: [ "closed" ]
  # branches: [ "dev" ]
  push:
    branches : ["dev"]

permissions:
  contents: read

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
  EC2_HOST: ${{ secrets.HOST }}
  EC2_SSH_USER: ubuntu
  PRIVATE_KEY: ${{ secrets.KEY }}
  CONTAINER_NAME: ssgserver

jobs:
  build-and-push-docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: create applicaion file
      run: |
        mkdir -p ./src/main/resources
        touch ./src/main/resources/application.yml
      
    - name: Set up application.yml
      run: echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64 . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:latest

    - name: Login to Docker Hub using Access Token
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push the Docker image
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}:latest

  deploy-to-ec2:

    needs: build-and-push-docker
    runs-on: ubuntu-latest
  
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_SSH_USER }}
        key: ${{ env.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          docker pull ${{ env.DOCKER_IMAGE_NAME }}
          docker stop server
          docker rm server
          docker run -d --name server -p 8080:8080 ${{ secrets.DOCKER_IMAGE_NAME }}
